<?xml version="1.0"?>
<!DOCTYPE Environments
[
	<!ELEMENT Environments ((Package|Application)+)>
	<!ELEMENT Application ((Server|Constants|Variables)+)>
		<!ATTLIST Application name CDATA #REQUIRED>
		<!ATTLIST Application namespace CDATA #REQUIRED>
		<!ATTLIST Application comment CDATA #IMPLIED>
	<!ELEMENT Package ((Server|Constants|Variables)+)>
		<!ATTLIST Package name CDATA #REQUIRED>
		<!ATTLIST Package namespace CDATA #REQUIRED>
		<!ATTLIST Package comment CDATA #IMPLIED>
	<!ELEMENT Server ((Constants|Variables)+)>
		<!ATTLIST Server ip CDATA #IMPLIED>
		<!ATTLIST Server interface CDATA #IMPLIED>
		<!ATTLIST Server hostname CDATA #IMPLIED>
		<!ATTLIST Server domain CDATA #IMPLIED>
		<!ATTLIST Server comment CDATA #IMPLIED>
	<!ELEMENT Constants (Constant+)>
		<!ATTLIST Constants prefix CDATA #IMPLIED>
		<!ATTLIST Constants comment CDATA #IMPLIED>
	<!ELEMENT Constant EMPTY>
		<!ATTLIST Constant name CDATA #REQUIRED>
		<!ATTLIST Constant value CDATA #REQUIRED>
		<!ATTLIST Constant type (string|long|boolean|double) "string">
		<!ATTLIST Constant comment CDATA #IMPLIED>
	<!ELEMENT Variables (Variable+)>
		<!ATTLIST Variables prefix CDATA #IMPLIED>
		<!ATTLIST Variables scope (request|executor) "request">
		<!ATTLIST Variables comment CDATA #IMPLIED>
	<!ELEMENT Variable EMPTY>
		<!ATTLIST Variable name CDATA #REQUIRED>
		<!ATTLIST Variable value CDATA #REQUIRED>
		<!ATTLIST Variable type (string|long|boolean|double) "string">
		<!ATTLIST Variable scope (request|executor) #IMPLIED>
		<!ATTLIST Variable comment CDATA #IMPLIED>
]>
<Environments>
	<Package name="Smarty" namespace="SMARTY" comment="Smarty template engine">
		<Constants>
			<Constant name="DIR" value="/home/project/webapp/classes/Smarty/" />
			<Constant name="TEMPLATE_DIR" value="/home/project/webapp/templates/" />
			<Constant name="COMPILE_DIR" value="/home/project/webapp/cache/Smarty/templates_c/" />
			<Constant name="CACHE_DIR" value="/home/project/webapp/cache/Smarty/cache/" />
			<Constant name="CONFIG_DIR" value="/home/project/webapp/classes/Smarty/configs/" />
		</Constants>
	</Package>
	<Package name="ADODB" namespace="ADODB">
		<Constants>
			<Constant name="DIR" value="/home/project/webapp/classes/adodb/" />
		</Constants>
		<Server ip="192.168." interface="eth0">
			<Variables>
				<Variable name="XXX" value="10" type="long" />
			</Variables>
		</Server>
	</Package>
	<Application name="www.yourdomain.com" namespace="prefix1" comment="xxx">
		<Constants>
			<Constant name="WEBAPP_ROOT" value="/home/project/webapp/" />
			<Constant name="CLASS_ROOT" value="/home/project/webapp/classes/" />
		</Constants>
		<Variables>
			<Variable name="vx1" value="10" type="long" />
			<Variable name="vx2" value="1.234" type="double" scope="executor" />
		</Variables>
		<Server ip="192.168." interface="eth0">
			<Constants>
				<Constant name="c1" value="true" type="boolean"/>
				<Constant name="c2" value="2" type="long" />
				<Constant name="c3" value="test" type="string" />
				<Constant name="c4" value="2.345" type="double" />
			</Constants>
			<Variables>
				<Variable name="v1" value="10" type="long" />
				<Variable name="v2" value="1.234" type="double" scope="executor" />
				<Variable name="v3" value="true" type="boolean" />
				<Variable name="v4" value="false" type="boolean" />
				<Variable name="v5" value="lance" type="string" />
				<Variable name="v6" value="lovette" scope="executor" />
			</Variables>
		</Server>
		<Server comment="xxx">
			<Constants prefix="xxx" comment="xxx">
				<Constant name="c5" value="1" type="boolean" />
				<Constant name="c6" value="c6v" />
				<Constant name="c7" value="c7v" comment="xxx" />
			</Constants>
			<Variables prefix="xxx" scope="executor" comment="xxx">
				<Variable name="v1" value="10" type="long" comment="xxx" />
			</Variables>
		</Server>
		<Server hostname="devserver">
			<Constants>
				<Constant name="c8" value="c8v" />
				<Constant name="c9" value="c9v" />
				<Constant name="c10" value="c10v" />
			</Constants>
		</Server>
		<Server domain="yourdomain.com">
			<Constants>
				<Constant name="c11" value="c11v" />
				<Constant name="c12" value="c12v" />
				<Constant name="c13" value="c13v" />
			</Constants>
		</Server>
		<Server domain="hotmail.com">
			<Constants>
				<Constant name="c31" value="c31v" />
				<Constant name="c32" value="c32v" />
				<Constant name="c33" value="c33v" />
			</Constants>
		</Server>
	</Application>
	<Application name="www.otherdomain.com" namespace="ff">
		<Server ip="192.168.0." interface="eth0">
			<Constants>
				<Constant name="c14" value="on" type="boolean"/>
				<Constant name="c15" value="v15v" />
				<Constant name="c16" value="v16v" />
			</Constants>
		</Server>
		<Server ip="10.10.0.">
			<Constants>
				<Constant name="c17" value="v17v" />
				<Constant name="c18" value="v18v" />
				<Constant name="c19" value="v19v" />
			</Constants>
		</Server>
		<Server>
			<Constants>
				<Constant name="c20" value="v20v" />
				<Constant name="c21" value="v21v" />
				<Constant name="c22" value="v22v" />
			</Constants>
			<Variables>
				<Variable name="v1" value="10" type="long" scope="executor" />
				<Variable name="v2" value="1.234" type="double" scope="executor" />
				<Variable name="v3" value="true" type="boolean" />
				<Variable name="v4" value="false" type="boolean" scope="executor" />
				<Variable name="v5" value="lance" type="string" scope="executor" />
				<Variable name="v6" value="lovette" />
			</Variables>
		</Server>
	</Application>
	<Application name="" namespace="">
		<Server ip="192.168.0." interface="eth0">
			<Constants>
				<Constant name="c14" value="on" type="boolean"/>
				<Constant name="c15" value="v15v" />
				<Constant name="c16" value="v16v" />
			</Constants>
		</Server>
		<Server ip="10.10.0.">
			<Constants>
				<Constant name="c17" value="v17v" />
				<Constant name="c18" value="v18v" />
				<Constant name="c19" value="v19v" />
			</Constants>
		</Server>
		<Server>
			<Constants>
				<Constant name="c20" value="v20v" />
				<Constant name="c21" value="v21v" />
				<Constant name="c22" value="v22v" />
			</Constants>
		</Server>
	</Application>
</Environments>